name: dcrnet-env4
channels:
  - nvidia
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - antlr-python-runtime=4.9.3
  - anyio=3.6.2
  - aom=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.1.0
  - async-timeout=4.0.2
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=5.0.1
  - blinker=1.5
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - cachetools=5.2.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - comm=0.1.2
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=11.6.0
  - cudnn=8.4.1.50
  - cycler=0.11.0
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gettext=0.21.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - google-auth=2.14.1
  - google-auth-oauthlib=0.4.6
  - grpcio=1.49.1
  - hydra-core=1.2.0
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.10.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.2.2
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libabseil=20220623.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.0.25
  - libcurand=10.3.2.56
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.14
  - libdrm=2.4.114
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgrpc=1.49.1
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=11.7.4.75
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2
  - libopenblas=0.3.21
  - libpciaccess=0.17
  - libpng=1.6.39
  - libprotobuf=3.21.9
  - libsodium=1.0.18
  - libstdcxx-ng=12.2.0
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libva=2.16.0
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.5
  - lz4-c=1.9.4
  - magma=2.5.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2022.1.0
  - multidict=6.0.2
  - nbclassic=0.5.4
  - nbclient=0.7.0
  - nbconvert=7.2.5
  - nbconvert-core=7.2.5
  - nbconvert-pandoc=7.2.5
  - nbformat=5.7.0
  - nccl=2.14.3.1
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - ninja=1.11.0
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.2
  - omegaconf=2.2.3
  - openblas=0.3.21
  - openh264=2.3.1
  - openssl=3.0.7
  - p11-kit=0.24.1
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - pooch=1.6.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.36
  - protobuf=4.21.9
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.13.0
  - pyjwt=2.6.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.19.2
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.8
  - pytorch=1.12.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=24.0.1
  - re2=2022.06.01
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scipy=1.10.1
  - send2trash=1.8.0
  - setuptools=65.6.3
  - six=1.16.0
  - sleef=3.5.1
  - sniffio=1.3.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.6.1
  - svt-av1=1.3.0
  - tbb=2021.8.0
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - werkzeug=2.2.3
  - wheel=0.38.4
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - thop=0.1.1
