checkpoints_dir: './checkpoints'
tensorboard_dir: './runs'
gpu: null
resume: false
save: True
evaluate: false
log_interval: 10
val_interval: 10
batch_size: 32
lr: 0.01
num_workers: 4
epochs: 100
version: 0.1
