checkpoints_dir: './checkpoints'
tensorboard_dir: './runs'
gpu: null
save: True
evaluate: false
log_interval: 10
val_interval: 10
batch_size: 200
lr: 0.1
num_workers: 4
epochs: 2500
reduction: 4
expansion: 1
version: 0.2
